dfx canister call bkyz2-fmaaa-aaaaa-qaaaq-cai create_user '("james", "emerald")'
dfx canister call bkyz2-fmaaa-aaaaa-qaaaq-cai create_user '("Irv", "emerald")'
dfx canister call bkyz2-fmaaa-aaaaa-qaaaq-cai create_user '("Ronald", "J")'
dfx canister call bkyz2-fmaaa-aaaaa-qaaaq-cai create_user '("Ben", "J")'
dfx canister call bkyz2-fmaaa-aaaaa-qaaaq-cai create_user '("Dix", "huit")'
dfx canister call bkyz2-fmaaa-aaaaa-qaaaq-cai create_user '("vingt", "huit")'